Инкремент 7 FIX
	--- FAIL: TestURLHandler_createShortApiURL (0.00s)
        	            	    --- FAIL: TestURLHandler_createShortApiURL/malformed_JSON (0.00s)
        	            	        handler_test.go:313: Expected response body 'URL is required
        	            	            ', got 'Invalid request body
        	            	            '
        	            	    --- FAIL: TestURLHandler_createShortApiURL/empty_body (0.00s)
        	            	        handler_test.go:313: Expected response body 'URL is required
        	            	            ', got 'Invalid request body
        	            	            '
        	            	FAIL